// <auto-generated />
using System;
using Infrastructure.Auth;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace PerformanceAnalysis.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260621164922_InitialAuthMigration")]
    partial class InitialAuthMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Auth.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Courseid")
                        .HasColumnType("integer")
                        .HasColumnName("courseid");

                    b.Property<int>("Directionid")
                        .HasColumnType("integer")
                        .HasColumnName("directionid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Projectid")
                        .HasColumnType("integer")
                        .HasColumnName("projectid");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex(new[] { "Courseid" }, "ix_groups_courseid");

                    b.HasIndex(new[] { "Directionid" }, "ix_groups_directionid");

                    b.HasIndex(new[] { "Name" }, "ix_groups_name")
                        .IsUnique();

                    b.HasIndex(new[] { "Projectid" }, "ix_groups_projectid");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("Domain.Auth.Refreshtoken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Createdat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<DateTime>("Expiresat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiresat");

                    b.Property<DateTime?>("Revokedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revokedat");

                    b.Property<string>("Tokenhash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tokenhash");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_refreshtokens");

                    b.HasIndex(new[] { "Tokenhash" }, "ix_refreshtokens_tokenhash");

                    b.HasIndex(new[] { "Userid" }, "ix_refreshtokens_userid");

                    b.ToTable("refreshtokens", (string)null);
                });

            modelBuilder.Entity("Domain.Auth.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatarpath")
                        .HasColumnType("text")
                        .HasColumnName("avatarpath");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<string>("Vkprofilelink")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vkprofilelink");

                    b.HasKey("Id")
                        .HasName("pk_students");

                    b.HasIndex(new[] { "Userid" }, "ix_students_userid")
                        .IsUnique();

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("Domain.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("Middlename")
                        .HasColumnType("text")
                        .HasColumnName("middlename");

                    b.Property<string>("Passwordhash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex(new[] { "Email" }, "ix_users_email")
                        .IsUnique();

                    b.HasIndex(new[] { "Login" }, "ix_users_login")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("StudentGroup", b =>
                {
                    b.Property<int>("Groupsid")
                        .HasColumnType("integer")
                        .HasColumnName("groupsid");

                    b.Property<int>("Studentsid")
                        .HasColumnType("integer")
                        .HasColumnName("studentsid");

                    b.HasKey("Groupsid", "Studentsid")
                        .HasName("pk_student_groups");

                    b.HasIndex(new[] { "Studentsid" }, "ix_student_groups_studentsid");

                    b.ToTable("student_groups", (string)null);
                });

            modelBuilder.Entity("Domain.Auth.Refreshtoken", b =>
                {
                    b.HasOne("Domain.Auth.User", "User")
                        .WithMany("Refreshtokens")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refreshtokens_users_userid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Auth.Student", b =>
                {
                    b.HasOne("Domain.Auth.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("Domain.Auth.Student", "Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_students_users_userid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudentGroup", b =>
                {
                    b.HasOne("Domain.Auth.Group", null)
                        .WithMany()
                        .HasForeignKey("Groupsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_groups_groups_groupsid");

                    b.HasOne("Domain.Auth.Student", null)
                        .WithMany()
                        .HasForeignKey("Studentsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_groups_students_studentsid");
                });

            modelBuilder.Entity("Domain.Auth.User", b =>
                {
                    b.Navigation("Refreshtokens");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
